name: silva_admin
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  get: ^4.6.1
  get_storage: ^2.0.3
  tflite_flutter: ^0.9.0
  camera: ^0.9.7+1
  path_provider: ^2.0.9
  path: ^1.8.0
  google_ml_kit: ^0.11.0
  image: ^3.0.2
  font_awesome_flutter: ^9.0.0
  url_launcher: ^6.0.3
  sqflite: ^2.0.2+1
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/images/
 
